### ISSUE TITLE
OAS 3: Flasgger seems not being able to resolve *components* reference when using yml file

### ISSUE THREAD

**Issue by vitodsk** [rochacbruno/flasgger#308]
Using an external yml file, even if adding as suggested app['SWAGGER']['openapi'] = '3.0.2',
it seems not being able to resolve the #/schemas/components reference:

`
My API is awesome......
tags:
  - My API
post:
  parameters:
    - name: user-id
      in: header
      description: Id of the user
      type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Users'

responses:
  200:
    description: something.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/UsersData'

components:
  schemas:
    Users:
      type: object
      properties:
          property1:
               type: string 
    UserData:
      type: object
      properties:
          property2:
               type: string

.........
...............
..............
`
on the Swagger page i get:
`
Errors
Hide
Resolver error at paths./v1/notifications/compute.post.responses.200.content.application/json.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /components/schemas/UsersData does not exist in document
`
the schema referred by `$ref: '#/components/schemas/Users'` is not shown at all and no errors are visualized for this

**Comment by ethaizone** [comment]
Add config to swagger like this.
`'optional_fields': ['components']`

If you found problems that `components` don't appear on root of json, you need to pass it as 
template` argument when you initial `Swagger` class instance. 

Create as `dict` and pass like this.
`swagger = Swagger(app, template=specs_dict)`

**Comment by homekeeper89** [comment]
Is this solved? I had a same problem and That way is not working.

**Comment by lcbm** [comment]
Not working here as well :frowning_face: 

**Flasgger version:** 0.9.5

Here are the **relevant parts of code** which include flasgger :point_down: 
```
# __init__.py
...
def create_app():
    app = flask.Flask(__name__, instance_relative_config=False)
    mymodule.config.configure_app(app)
    flasgger.Swagger(app)
...

# config.py
...
    SWAGGER = {
        "uiversion": 3,
        "openapi": "3.0.3",
        "info": {
            "title": "Ball Metrics Microservice API",
            "description": "API to compute statistical metrics and generate plottable data based Ball's data.",
            "version": "0.1.0",
        },
        "optional_fields": ['components'],
    }
...
```

**OpenAPI Specification yaml**... `response 400` (which uses `components`) does **NOT** work, while the `response 500` (which has the same specification as the 400 one and doesn't use `components`) works. Also, to be clear, I tried some variations of the code below. :point_down: 

```
# availability_graph.yml
...
responses:
  400:
    description: Bad Request
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
  500:
    description: Internal Server Error
    content:
      application/json:
        schema:
          type: object
          properties:
            error:
              type: object
              properties:
                description:
                  schema:
                    type: string
                  description: A message which describes the error that occured
                  example: "An unexpected error occurred"
                message:
                  schema:
                    type: string
                  description: A message which describes the source of the error
                  example: "Internal server error"
                status_code:
                  schema:
                    type: integer
                  description: HTTP status code related to the error
                  example: 500
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            description:
              schema:
                type: string
              description: A message which describes the error that occured
              example: "An unexpected error occurred"
            message:
              schema:
                type: string
              description: A message which describes the source of the error
              example: "Internal server error"
            status_code:
              schema:
                type: integer
              description: HTTP status code related to the error
              example: 500
```

**Output** :point_down: 
![image](https://user-images.githubusercontent.com/31375047/98307223-0e4da800-1fa4-11eb-9d74-adef62991d2b.png)

**Error** :point_down: 
![image](https://user-images.githubusercontent.com/31375047/98306948-91223300-1fa3-11eb-873e-c0e3ae266199.png)

**Comment by vankillua** [comment]
I found a way to using `$ref: '#/components/schema/xxx'`

### Compatible with OpenAPI2 and OpenAPI3

```python
    SWAGGER = {
        'openapi': '3.0.2',
        'title': 'Test APi',
        'description': 'Test API Document',
        'version': '1.0.0',
        'termsOfService': None,
        'definitions': load_all_definitions(),
        'components': {
            'schema': load_all_definitions()
        }
    }
```

The function of `load_all_definitions` is to load all the `definitions` yaml file or json file

### Using docstrings as specification

![image](https://user-images.githubusercontent.com/20939027/99356701-88a3f380-28e5-11eb-8240-25021a3af3d4.png)

### Output

![image](https://user-images.githubusercontent.com/20939027/99356582-5c887280-28e5-11eb-8ae9-8ba7b3896d53.png)

**Comment by Lounarok** [comment]
@all This issue should be fixed by #505

**Comment by gabriel-viviani** [comment]
Hey @Lounarok just as feedback, I'm still facing same issue, flask_app.config:
`'SWAGGER': {'title': "Tittle", 'uiversion': 3, 'openapi': '3.0.2', 'optional_fields': ['components']}`
